In [1]:
import numpy as np

## Numpy 길라잡이 1

### 넘파이 어레이 선언

In [3]:
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a.shape #열벡터를 떠올리면 이해가 좀 더 쉬울지도?

(4,)

In [5]:
a+1,a*2,a/2

(array([2, 3, 4, 5]), array([2, 4, 6, 8]), array([0.5, 1. , 1.5, 2. ]))

### 넘파이 어레이 인덱싱 기초

#### 1차원 어레이

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a[0],a[1],a[2],a[3],a[-1],a[-2],a[-3],a[-4] #일반 리스트와 얼추 비슷

(1, 2, 3, 4, 4, 3, 2, 1)

리스트 스트라이딩

In [8]:
a[1:3] #2 번 부터 4번 전까지 (반 열린집함을 떠올리면 편함)

array([2, 3])

In [9]:
#a를 조금만 더 확장 해보도록하겠음
a = np.array([11,22,33,44,55,66])

정수 배열에 의한 인덱싱

In [10]:
a[[0,2,4]] #꺾쇠 하나면 호출 안됨, 이유는 차원때메 그런듯

array([11, 33, 55])

Bool 을 통한 인덱싱

In [11]:
a[[True,True,True,False,True,False]] #잘 되는 모습

array([11, 22, 33, 55])

In [12]:
a[[True,True,True,False,True]] #갯수 안맞으면 안되는 모습

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5

In [ ]:
a < 33 #참 거짓을 나타내주는 논리 연산자

In [ ]:
a[a<33] #논리 연산자의 결괏값은 결국 Bool

#### 2차원 어레이

In [ ]:
A = [[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
A2 = np.array(A)
A2

In [ ]:
A2.shape #4행 4열 2차원인 모습

In [ ]:
A #그냥 파이썬 기본 기능 중첩리스트

#### 2차원 어레이 인덱싱

In [ ]:
A2[0][0], A[0][0] #같은값

In [ ]:
A2[0][1], A[0][1] #같은값

In [ ]:
A2[-1][0], A[-1][0] #같은값

In [ ]:
A2[1,1] #넘파이 어레이는 잘 됨

In [ ]:
A[1,1] #얜 안됨

In [ ]:
#정수 배열을 통한 인덱싱과 스트라이딩
#참고로 넘파이 어레이만 되는 기능
A2[0,0:2]

In [ ]:
A2[0].shape #1행

In [ ]:
A2[0,:].shape #얘도 1행 , 1행의 모든 열 원소 호출 = 1행

In [ ]:
A2[[0,2],:] #1,3행

In [ ]:
A2[[0,2]]

In [ ]:
#그냥 팁 꺾쇠를 겹쳐 쓰면 차원을 보존할 수가 있다

In [ ]:
A2[[1],0] #얘는 넘파이 어레이 크기 1짜리

In [ ]:
A2[1,0] #얘는 스칼랏값, 차원이 보존되지 않았다

In [ ]:
A2[:,0] # 1열 단순 나열 (1차원)

In [ ]:
A2[:,[0]] # 1열 , 차원이 2차원으로 보존(꺽쇠 두개들가있음)

In [ ]:
A2[:,[0,2]] # 1열, 3열 

In [ ]:
A2[0:2,[0,2]] #1,2행과 1열,3열 좌표

In [ ]:
A2[0:2,0:3] #그냥 해봄

#### 꼭 np.array()를 리스트로만 받아야 하나?

`a`: 아니다

In [13]:
np.array((1,2,3)) #튜플 가능

array([1, 2, 3])

#### 특정 값을 지닌 넘파이 어레이를 만들어주는 메서드

In [14]:
np.zeros(3) #영벡터

array([0., 0., 0.])

In [15]:
np.ones(4) # 모든 원소가 1인 4차원짜리 벡터

array([1., 1., 1., 1.])

In [16]:
np.linspace(0,1,12) #0부터 1까지 12개로 쪼개기 길이도 12임

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.array(range(10)) #같은 기능이다

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshape

In [22]:
a.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

In [24]:
a #저장이 되는 기능이 아님.. 변수를 새로 선언 해야함

array([11, 22, 33, 44, 55, 66])

In [26]:
a_rshpd = a.reshape(2,3)
a_rshpd

array([[11, 22, 33],
       [44, 55, 66]])

In [27]:
a_rshpd.reshape(-1) # 원상 복귀

array([11, 22, 33, 44, 55, 66])

#### -1을 이용한 reshape

In [30]:
a= np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [32]:
a.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

`-` 공배수 단위에서 -1을 함께 넣으면 앞 숫자에 맞춰 reshape해줌

#### 2차원 배열 선언

In [36]:
np.zeros((3,3)) #영행렬

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((3,3)) # 1로만 원소로 이루어진 행렬

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(4) #4x4 단위행렬

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.diag([1,2,3,-1]) #안에 있는 argument 만큼의 차원의 대각행렬

array([[ 1,  0,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  0, -1]])

### numpy를 이용한 난수생성

In [44]:
np.random.randn(10) #표준 정규 분포의 난수 10개

array([-0.22226475, -2.20725764, -0.34544573, -1.28394361,  0.40124846,
       -0.31926913,  0.01612964,  0.39066971, -0.83542309,  0.32888646])

In [46]:
np.random.rand(10) # 0~1사이에서 난수 10개 Uniform distribution

array([0.32080851, 0.49221091, 0.71895607, 0.75011362, 0.50697294,
       0.81474109, 0.74667768, 0.78577036, 0.98459071, 0.38053399])

`-` 난수를 생성함과 동시에 차원을 만들어보자

In [48]:
np.random.randn(10).reshape(2,5)

array([[-0.46422979,  0.622728  , -1.77122408, -0.21308197, -0.50968175],
       [ 1.33199674, -0.9406342 ,  0.39775098,  0.81742168,  0.03491051]])

### 행렬에 관련된 Numpy의 기능

In [52]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [54]:
A.T #전치행렬

array([[0, 2],
       [1, 3]])

In [56]:
np.linalg.inv(A) # 앞의 메서드는 역행렬을 구해줌

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

## Numpy 길라잡이 2

In [59]:
A = np.array([[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]])
A

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [60]:
np.linalg.inv(A)@np.array([3,3,3,3])

array([1., 1., 1., 1.])

In [61]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

`-` 행렬곱

행렬곱은 앞 행렬의 열의 갯수와 뒷 행렬의 행의 갯수를 맞추는 것이 일반적이다.

In [67]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2]).reshape(2,1) 
A@b

array([[ 5],
       [11]])

In [68]:
A.shape, b.shape, (A@b).shape

((2, 2), (2, 1), (2, 1))

In [69]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2]).reshape(1,2) 
b@A 

array([[ 7, 10]])

In [70]:
A.shape, b.shape, (b@A).shape

((2, 2), (1, 2), (1, 2))

In [71]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2]).reshape(2,1) 
b@A #성립하지 않을 것이다.

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

근데 행렬곱을 할 때 쓰이는 '@' 는 벡터와 사용시 어느정도 유연성을 부여한다

In [73]:
A = np.array([1,2,3,4]).reshape(2,2)
b = np.array([1,2]) 
A@b

array([ 5, 11])

In [75]:
A.shape , b.shape , (A@b).shape

((2, 2), (2,), (2,))

`-` 위에선 b라는 벡터를 2*1 행렬로 본 듯 하다

In [78]:
b@A

array([ 7, 10])

In [79]:
A.shape , b.shape , (b@A).shape

((2, 2), (2,), (2,))

2x2 @ 2x1로 해석한 후 (2,)로 만든 것 같다

1차원 짜리 벡터에 차원의 유연성을 주었다고 볼 수 있다

In [84]:
b1 = np.array([1,2,3,4])
b2 = np.array([1,2,3,4])
b1@b2

30

In [85]:
b1.shape , b2.shape , (b1@b2).shape

((4,), (4,), ())

1x4 @ 4x1 로 보고 내적을 시행한 것 같다

4x1 @ 1x4로 행렬을 내고 싶다면?

In [90]:
b1_ = b1.reshape(4,1)
b2_ = b2.reshape(1,4)
b1_@b2_ #직접 Reshape 을 해준 다음에 보아야한다.

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

`-` 재미는 없는데 재미있는 점

In [92]:
b1@b2

30

In [93]:
b1.reshape(1,4)@b2.reshape(4,1)

array([[30]])

`-` 굳이 reshape를 써주면 차원이 보존된다

In [96]:
(b1@b2).shape, (b1.reshape(1,4)@b2.reshape(4,1)).shape

((), (1, 1))

### 차원

`-` 넘파이 어레이의 차원을 확인하고 싶다면 .shape를 써버리면 그만이다.

In [99]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [101]:
a.shape #24짜리 열벡터로 보는 것이 맘이 편할듯 하다

(24,)

`-` 차원의 미묘함을 느껴보자

In [108]:
a= np.array(3.14) #0 차원
a,a.shape

(array(3.14), ())

In [109]:
a= np.array([3.14]) #1차원
a,a.shape

(array([3.14]), (1,))

In [110]:
a= np.array([[3.14]]) #2차원
a, a.shape

(array([[3.14]]), (1, 1))

### 축 #Axis

### Concatenate

### 1차원

In [120]:
a= np.array([1,2])
b= -a

In [114]:
a.shape , b.shape

((2,), (2,))

In [116]:
np.concatenate([a,b]) , np.concatenate([a,b]).shape

(array([ 1,  2, -1, -2]), (4,))

In [117]:
a=np.array([1,2])
b=-a 
c=np.array([3,4,5])

In [118]:
np.concatenate([a,b,c]) , np.concatenate([a,b,c]).shape

(array([ 1,  2, -1, -2,  3,  4,  5]), (7,))

#### 2차원

In [122]:
a = np.arange(4).reshape(2,2)
b= -a

In [130]:
np.concatenate([a,b]), np.concatenate([a,b]).shape

(array([[ 0,  1],
        [ 2,  3],
        [ 0, -1],
        [-2, -3]]),
 (4, 2))

`관찰:` 2행2열 , 2행2열 -> 4행 2열

In [131]:
np.concatenate([a,b],axis = 1), np.concatenate([a,b],axis = 1).shape 

(array([[ 0,  1,  0, -1],
        [ 2,  3, -2, -3]]),
 (2, 4))

`관찰:` 2행 2열 , 2행 2열 -> 2행 4열

0이라는 axis를 사용한다면 행에 붙고 

1이라는 axis를 사용한다면 열에 붙는 것 처럼 보임

또한 Axis의 값은 차원의 갯수를 넘을 수 없다.

### 확장

In [135]:
a=np.array(range(2*3*4)).reshape(2,3,4)
a, a.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 (2, 3, 4))

In [136]:
b= -a

In [137]:
b, b.shape

(array([[[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],
 
        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]]]),
 (2, 3, 4))

In [142]:
zero_ = np.concatenate([a,b], axis=0 )
zero_ , zero_.shape #4덩어리 3행 4열

(array([[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]],
 
        [[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],
 
        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]]]),
 (4, 3, 4))

In [144]:
one_ = np.concatenate([a,b], axis=1)
one_ , one_.shape #2덩어리 6행 4열

(array([[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23],
         [-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]]]),
 (2, 6, 4))

In [146]:
two_ = np.concatenate([a,b], axis= 2)
two_ , two_.shape #2덩어리 3행 8열

(array([[[  0,   1,   2,   3,   0,  -1,  -2,  -3],
         [  4,   5,   6,   7,  -4,  -5,  -6,  -7],
         [  8,   9,  10,  11,  -8,  -9, -10, -11]],
 
        [[ 12,  13,  14,  15, -12, -13, -14, -15],
         [ 16,  17,  18,  19, -16, -17, -18, -19],
         [ 20,  21,  22,  23, -20, -21, -22, -23]]]),
 (2, 3, 8))

axis= 는 인덱싱과도 같고 지명하는 부분의 차원을 늘린다

#### 번외

In [149]:
a= np.array(1)
b= np.array(-1)

In [150]:
a.shape , b.shape

((), ())

In [152]:
np.concatenate([a,b]) #지명할 차원이 없다

ValueError: zero-dimensional arrays cannot be concatenated

`-` 꼭 같은 차원이여야만 하나?

In [154]:
a= np.arange(4).reshape(2,2)
b= np.array([5,6]).reshape(2,1)

In [156]:
np.concatenate([a,b],axis= 1) #된다

array([[0, 1, 5],
       [2, 3, 6]])

In [158]:
np.concatenate([a,b],axis= 0) #안된다

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [159]:
a= np.arange(10)
b= -a

In [160]:
a.shape, b.shape

((10,), (10,))

In [164]:
np.concatenate([a,b]) , np.concatenate([a,b]).shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0, -1, -2, -3, -4, -5, -6,
        -7, -8, -9]),
 (20,))

### 관심사 : 3개 짜리 벡터를 붙여서 3행 2열을 만들고 싶다



In [167]:
a= np.array([1,2,3])
b= -a

In [169]:
np.concatenate([a,b]) #아니고..

array([ 1,  2,  3, -1, -2, -3])

In [171]:
np.concatenate([a.reshape(3,1),b.reshape(3,1)],axis = 1) #성공

array([[ 1, -1],
       [ 2, -2],
       [ 3, -3]])

#### 딱 정하고 가자

차원이 하나인 numpyarray는 (n,)로 차원이 표기 되는데 그냥 1차원 벡터로 이해를 하자. 행이나 열을 부여하게 되면 뭔가 이해가 더뎌진다

`관찰:` 저렇게 축을 일일히 reshape 시킨다음에 하려니까 너무 귀찮다.

### Stack

In [176]:
a=np.array([1,2,3])
b=-a

In [177]:
np.stack([a,b],axis=0)

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [178]:
np.stack([a,b], axis = 1)

array([[ 1, -1],
       [ 2, -2],
       [ 3, -3]])

`-` 얘는 concatenate와 달리 차원의 갯수가 늘어버린다

In [180]:
a.shape

(3,)

axis=0으로 설정을 해서 stack을 한 결과 2,3이 되었고, axis=1로 한 결과 3,2 가 되었다

axis=0 -> shape의 0번 째 자리에 축이 추가가 되고 거기를 기준으로 붙는다

axis =n -> shape의 n번 째 자리에 축이 추가가 되고 거기를 기준으로 붙는다.

In [183]:
a=np.arange(3*4*5).reshape(3,4,5) 
b=-a

In [184]:
zero__ = np.stack([a,b],axis=0)
one__ =np.stack([a,b],axis=1)
two__= np.stack([a,b],axis=2)
three__ = np.stack([a,b],axis=3)

In [185]:
zero__.shape , one__.shape , two__.shape , three__.shape

((2, 3, 4, 5), (3, 2, 4, 5), (3, 4, 2, 5), (3, 4, 5, 2))

`-` 필히 외울 것 ㅋ

### Sum

In [189]:
a= np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [190]:
a.sum(axis=0) , a.sum(axis= 1)

(array([20, 25]), array([ 1,  5,  9, 13, 17]))

`-` 0은 행을 긁어 합, 1은 열을 긁어 합

In [192]:
a.sum(axis=(0,1)) #행과 열을 다 긁는다면

45

### Mean

In [195]:
a.mean(axis=0) #행을 긁어 평균, 즉 2개가 나올 것임

array([4., 5.])

In [196]:
a.mean(axis= 1 ) #열을 긁어 평균, 즉 5개가 나올 것임

array([0.5, 2.5, 4.5, 6.5, 8.5])

In [197]:
a.mean()

4.5

In [199]:
a.mean(axis=(0,1)) #행과 열을 다 긁는다면

4.5

### Standard deviation

In [201]:
a=np.array([1,2,3,4])
a.std()

1.118033988749895

In [202]:
np.sqrt(sum((a-a.mean())**2)/4)

1.118033988749895

### 표본 표준편차 (자유도 발생)

In [204]:
a=np.array([1,2,3,4])
a.std(ddof=1)

1.2909944487358056

In [205]:
np.sqrt(sum((a-a.mean())**2)/3)

1.2909944487358056

### Argmax, Argmin

#### 1차원

In [213]:
a= np.array([1,6,7,3,5,23,656])
a

array([  1,   6,   7,   3,   5,  23, 656])

In [212]:
a.argmax() , a.argmin() #가장 크거나 작은 것이 있는 위치를 알려준다

(6, 0)

#### 2차원

In [216]:
np.random.seed(43052)
a=np.random.randn(4*5).reshape(4,5)
a

array([[ 0.38342049,  1.0841745 ,  1.14277825,  0.30789368,  0.23778744],
       [ 0.35595116, -1.66307542, -1.38277318, -1.92684484, -1.4862163 ],
       [ 0.00692519, -0.03488725, -0.34357323,  0.70895648, -1.55100608],
       [ 1.34565583, -0.05654272, -0.83017342, -1.46395159, -0.35459593]])

In [218]:
a.argmax() , a.argmin() #이것도 행과 열을 다 긁어버린 상태로 위치를 내주는 것 같다

(15, 8)

In [220]:
a.argmax(axis=0) , a.argmax(axis=1) #행 긁어서 최대, 열 긁어서 최소

(array([3, 0, 0, 2, 0], dtype=int64), array([2, 0, 3, 0], dtype=int64))